<?php
require_once("models/config.php");
if (!securePage($_SERVER['PHP_SELF'])){die();}
require_once("models/header.php");

echo "
</div>
<div id='main' class='col-md-10'>
<div class='instruction'>
<h1>procus user manual</h1><br />
<p class='text-center'><img src='logo.png' width='300' height='300' /></p>
<p class='lead'><a href='docs/Instruction.pdf'>Download PDF</a></p>
<p class='lead'>Table of contents:</p>
<a name='content'></a>
<ol><li><strong><a href='#a1'>Introduction</a></strong></li>
	<li><strong><a href='#a2'>Theory</a></strong></li>
	<ul><li><em><a href='#a3'>What is procrastination and why do we procrastinate?</a></em></li>
		<li><em><a href='#a4'>Comfort zone</a></em></li>
		<li><em><a href='#a5'>Inner resistance</a></em></li>
		<li><em><a href='#a6'>Brain illusions</a></em></li>
		<li><em><a href='#a7'>&ldquo;I have to&rdquo;</a></em></li>
	</ul><li><strong><a href='#a8'>Stage 1</a></strong></li>
	<ul><li><em><a href='#a9'>Why you cannot overbear</a></em></li>
		<li><em><a href='#a10'>TRS</a></em></li>
		<li><em><a href='#a11'>Learning to determine the inner resistance</a></em></li>
		<li><em><a href='#a12'>First steps</a></em></li>
		<li><em><a href='#a13'>Future Plans</a></em></li>
		<li><em><a href='#a14'>Reminders</a></em></li>
		<li><em><a href='#a15'>Breakdowns</a></em></li>
	</ul><li><strong><a href='#a16'>Stage 2</a></strong></li>
	<ul><li><em><a href='#a17'>New goals</a></em></li>
		<li><em><a href='#a18'>Making detailed plan</a></em></li>
		<li><em><a href='#a19'>One more trap</a></em></li>
		<li><em><a href='#a20'>Looking for a partner</a></em></li>
		<li><em><a href='#a21'>Breakdowns again</a></em></li>
	</ul><li><strong><a href='#a22'>The last stage</a></strong></li>
	<ul><li><em><a href='#a23'>Implement the initial purpose</a></em></li>
		<li><em><a href='#a24'>Do it now</a></em></li>
		<li><em><a href='#a25'>Recommendations</a></em></li>
	</ul><li><strong><a href='#a26'>Afterword</a></strong></li></ol>
<h2><a name='a1' href='#content'><strong>Introduction</strong></a></h2>
<p>There are two options on how to read this manual. The first is that you will read only during your work, step by step, not looking ahead. On the one hand, it will consider some of the points discussed at the end from the very beginning, but the assignments mentioned in the end can scare away those who are not fully convinced that there is something to change. The second is that you look at all at once. Then you will need to re-read the manual at least once a week. It is up to you.</p>
<p>Speaking straightforward, this system will not help you cure procrastination quickly and magically. Your procrastination has evolved at once, hasn&rsquo;t it? It will not be easy to get through. This system is not a supernatural solution for those who suddenly started to study for exams, suddenly look for a job, or suddenly do something else. I assume that if you were in your comfort zone for so long, doing nothing, then you can be there for quite a while more before any changes. Do not be surprised if the first goals in this instruction will be so trivial and simple. This system has been developed to cure procrastination in critical stages. Although, of course, it can be used by anyone, but I have taken care of those who systematically delay and it seriously affects their lives. The rest of users have to adopt some parts of this tutorial for their individual situation. In addition, I have to say that my objective is not to drastically change your life. You will decide what to change yourself.</p>
<p>In my personal experience, procrastination seriously affected my life, almost ruining it, for three times. Once I managed to escape almost miraculously, and in the other two cases, I had to overbear and get through. Even excluding these key events, procrastination has brought me a lot of harm in other small things. Frankly, I have to admit that I did not get rid of procrastination completely. Moreover, it is doubtful that I ever will. It was built inside us at the brain level. Now I just do not let procrastination ruin my life. I am struggling it and fighting successfully. At least one of the proofs is this very instruction and the system itself. If I had continued to procrastinate, I would never have done it.</p>
<h2><a name='a2' href='#content'><strong>Theory</strong></a></h2>
<h3><a name='a3' href='#content'><em>What is procrastination and why do we procrastinate?</em></a></h3>
<p>As you may know, procrastination is a model of behavior in which a person delays any business until unlimited &ldquo;later&rdquo;. We should not consider procrastination as an issue itself. We procrastinate because of different causes. There are many reasons and I cannot list all of them, and maybe I do not know all of them. Anyway, it does not matter. The inner voice of procrastination is quite complicated. I will try to draw a simple procrastination scheme and explain why we delay. To do that, I need to add some theory and concepts here.</p>
<h3><a name='a4' href='#content'><em>Comfort zone</em></a></h3>
<p>Comfort zone is an expression used in psychology. It has slightly different explanations, but they are quite similar. I will describe what exactly I understand and mean by this phrase. It may be different from what you have heard from other sources. Comfort zone is a summation of all the familiar actions, habits and everything that you do regularly. Roughly speaking, this is what you used to do every day. Any of these actions cannot cause any negative emotions (there are some exceptions). Usually, a person is trying to reach comfort zone on influence of stresses, problems, bad mood and so on. Curiously enough, people who have no social life are in their comfort zone all the time. All that we delay is out of our comfort zone.</p>
<p>Every human being has a unique comfort zone. I am making a note here: a comfort zone may not be literally a &ldquo;comfort&rdquo; one. Firstly, a comfort zone cannot be easy or hard. For example, it may contain something like morning jogging. For some people it seems not so comfortable, but the person who really has this habit may feel discomfort, anxiety, and other unpleasant feelings if he or she will not run one day. Second, a comfort zone surprisingly can cause the most discomfort. For example, people whose comfort zone is narrow (i.e., includes a very small amount of activities) may experience discomfort from the fact that their life rolls down even further in the meantime. Instead of desired and useful things, the person plays computer, watching series or doing something else. Conventional procrastinators has no such thing but those whose lives spoiled enough, can have this condition.</p>
<p>Again, in the ordinary we procrastinate over those things that are not in our comfort zone. Because outside the comfort zone we experience stress and unpleasant feelings (not necessarily that they are strong). That is how our brain works, same way for many people. The narrower our comfort zone is, the fewer times we get beyond it, the harder is our discomfort when we do something different. However, any comfort zone is expandable. In fact, that is what we will do using the system.</p>
<p>Once again, I note that if a person does something that is out of comfort zone, the person is experiencing unpleasant feelings, emotions, etc. They are stronger, if this person is strongly used to actions within their comfort zone. To give an example, if a person is used to play computer games (for example, 5 hours per day), and if it will not be possible for this person to play, he or she will feel discomfort, anxiety, and so on.And if someone is used to play 15 hours per day, and it happens that this guy cannot play at all, it will lead him to despair. I am sure many of us have come across the news that some people commit suicide when they miss the opportunity to play at all.</p>
<h3><a name='a5' href='#content'><em>Inner resistance</em></a></h3>
<p>Here I have to enter one more notion: the inner resistance. I have not seen this term anywhere before, especially in this way, although I do not deny the possibility that it was already used for a long time somewhere else. This phrase came up to describe some experience in my own procrastination, which for some reason all the authors I read kept silent about, and which, as I thought, experiencing every procrastinator (and later, I was convinced by asking my friends). Understanding the internal resistance is very important for your future work, so I decided to give it some special attention and, despite the fact that it is closely intersects with comfort zone, consider separately.</p>
<p>Thus, the internal resistance is all the unpleasant, negative feelings and emotions that we feel when we have to do some stuff. For some people it is a small (or large) obstacle, through which they can easily step over or with some effort; for others it is an undefeatable barrier, indestructible wall.</p>
<p>To make it clearer, imagine that you have to make 20 push-ups right now. Do you feel it? If you are not used to doing exercise, you felt some inner resistance to this. The strength of this resistance depends on two factors. Firstly, on how often you do anything contrary to this inner resistance. Secondly, on how the case is difficult for you (emotionally), how it is unspecified (do you know what exactly you have to do or not), how boring it is, etc. The stronger inner resistance is, the harder is to start doing something, the more we procrastinate.</p>
<h3><a name='a6' href='#content'><em>Brain illusions</em></a></h3>
<p>In addition, a few more points that are important and related to our brain that contribute to procrastination. The first is that our brain is exposed to a variety of illusions. I will tell about one. It is quite tricky to describe, but I will try. The illusion is that men cannot adequately assess their future condition, state. A person thinks, or rather, feels that over time he or she will be ready to do the work that is postponed now. Although, sometime after this, this person will continue to feel the inner resistance and procrastinate. Despite the fact that our experience says that we will seek to postpone a case until the last moment again and again, we continue to be conducted on this illusion. I have to confess that I still can find myself caught in this trap from time to time, although it happens much less. It is an insidious trap; I will say more about it later.</p>
<p>The second point is that for the brain, it is almost equivalent if you get the job done or delay it for later. Now I will try to explain. Here is the work that you need to do. When a person facing the task (in all the meanings of the word), which must be done right now, there is some tension. This person always seeks to avoid this stress, as it naturally works in the brain. There are two solutions for this problem: first - to do what has to be done, and the second is to postpone it for later. If the task is still hanging in front (if it is not quite soon), the brain does not sees it as a problem. In both cases, the brain will produce endorphins. I assume you felt it more than once. Remember that you had some important business, which you did not liked; you did not wanted to do it. And you delayed. Did you noticed that you have a sense of relief; has it increased the mood; did you enjoyed? If your thing that you had to do was difficult and if it was not necessary to carry out urgently, perhaps your condition was as I described. That is the problem. Considering that, once again, both options (to do now or postpone) are equivalent for the brain in some sense, you choose rather to delay, since it does not have to exert any effort now and avoid stress as fast as possible.</p>
<h3><a name='a7' href='#content'><em>&ldquo;I have to&rdquo;</em></a></h3>
<p>There is another important point. We all have one bad feature. The fact is that when we have something to do, we have an additional barrier inside, more increasing the inner resistance. There is no such thing when we want to do something, but we do not have to. However, this occurs even when we have something we want to do, we like it, but then we are telling ourselves that we should do it. That is it, motivation slowly disappears, and desire to do it disappears as well if it is not something that we want very much.</p>
<p>What is the reason? In my opinion, the roots are coming from the childhood and particularly puberty. Parents and society, were constantly told us that we have to do something. In accordance with the period we had, we woke rebellious spirit, and we were saying ourselves: &quot;No, I do not have to,&quot; or something similar. In any case, we were forced or we were able to escape, but a negative association is firmly entrenched in our brains. Every time we are told to do something, these associations comes up. If we wanted to do a thing before, perhaps we do not want it after we have been told to do it.</p>
<p>What to do? Honestly, I do not know. I am not sure it is possible to change at all. However, the very attention to this point, I believe, should be given, because knowing about it already provides at least some benefit (forewarned is forearmed). There is, however, one technique of Rational Emotive Behavior Therapy (REBT), which allows make this association weaker. Speaking from experience, sometimes it is possible. However, REBT is applied to slightly other &quot;must&quot; and on the other sense.</p>
<p>For example, I also initially told myself that I have to write the system and this guide. It was a bit complicated, but I managed to handle it.</p>
<p>The technique consists in the fact that we are changing all the &quot;I have to&quot; to &quot;I want to.&quot; Sounds simple, right? However, it is not so easy to convince yourself. You either what it from the beginning, or not. Therefore, we have to convince ourselves that we do it because we want it ourselves, not because we need it. However, it is better not to convince ourselves that we have to do something. But this is a double edged sword.</p>
<p>And yes, I know that in the text below there will be a lot of &quot;should&quot;, &quot;must&quot;, and &ldquo;have to&rdquo;, but it is the nature of the language and I have no idea how to cheat here.</p>
<h2><a name='a8' href='#content'><strong>Stage 1</strong></a></h2>
<h3><a name='a9' href='#content'><em>Why you cannot overbear</em></a></h3>
<p>As I said in the beginning, do not expect quick results. Why cannot we change ourselves quickly and decisively? Your procrastination evolved not in a single day, it is the basis of the brain. Overbearers are trying to do many things that are beyond their comfort zone at once, but also (and this is worse) trying to stop doing things that were in the comfort zone in the beginning. When you experience severe stress and other &quot;pleasant&quot; experience related to violation of a strong comfort zone, then you begin to pull back, motivation disappears, it is necessary to relax at this point... And you break down, run into the comfort zone (computer games, series, and other things and so on.), Even more than you were before. When you realize that you have broken, the time has already passed; it is more difficult to overbear once more, you have way less motivation. Fail. If you ever tried quickly and radically change yourself, then I am sure you know very well what I am talking about.</p>
<p>That is why I propose to change gradually, without haste. We have to retrain our brains a bit. It is not fast and not as easy as we would like, but it is possible.</p>
<h3><a name='a10' href='#content'><em>TRS</em></a></h3>
<p>I want to tell you about one technique. Initially, it was used by behaviorists (it is quite old). They called it Token Reward System. The word &quot;reward&quot; here is has a conditional meaning, not literal. The technique is very simple to use. There is a huge variety of options of its execution. I will tell you about the version used in ProCuS, you are free to use either it or come up with a slightly different, but it is important to comply with certain conditions (of which below).</p>
<p>The technique consists in the fact that you symbolically fix the results somewhere. In turn, the meaning is that you clearly see the results. And this is very important. You cannot keep constantly in mind and list all your accomplishments, which is fatal for any changes in yourself, because motivation is rapidly eroding, resulting to fail. When we see completely everything that we have done, with the proviso that we feel some changes in ourselves, it motivates our further activity. Therefore, this technique is extremely important, without it, I can guarantee a failure.</p>
<p>ProCuS provides a board with the limit of 200 records. Every time you made a step in your fight with procrastination &ndash; put a record on your board. Each record has its own meaning. Records themselves are be differentiated depending on how important and complex action you have done. In this system, it is difficulty level on a scale of five. A color represents the difference level. There is light green records for simple tasks and the greener it is, the more important was the action you have done.</p>
<h3><a name='a11' href='#content'><em>Learning to determine the inner resistance</em></a></h3>
<p>The first thing you will need to take into account, besides the obvious significance and importance of the action - the inner resistance, about which I have already spoken. So first you have to learn about its pricing. Call it a linear inner resistance (the LIR). To do this, take a sheet of paper and draw a line on it.</p>
<p>At the left end is the least level of inner resistance, just imagine the things that you regularly do and do not experience any negative feelings inside (computer games or series, for example, if you are playing or watching something in general, or anything else like that). Note the point. The right end is the maximum inner resistance, which you can imagine. It is difficult to give any precise example because it is very individual. So think for yourself, just remember, it must have a maximum internal resistance, impenetrable wall, causing a large level of anxiety or other negative feelings. Have you imagined? Put a point on the right edge of the line. Then, divide line by 10 approximately equal intervals. Try testing the line, representing a variety of business (cleaning, going out, exercise), estimating the internal resistance (which is why it is necessary to imagine very well), and noting the results of the evaluation on the line. Then we will come back to this.</p>
<p>And yes, I realize that our TRS may seem simple and not serious if you have no experience in it. But speaking as a person who tested it in himself and saw how the others were using it (not only with procrastination issues, it is used in so many areas like bad habits treat or sport activities) if run it properly, it really works.</p>
<h3><a name='a12' href='#content'><em>First steps</em></a></h3>
<p>The first step on our way to beating procrastination is having a board. You have to go to the registration page and create an account. You will get your board automatically. I am serious. This is the only way. Therefore, put aside reading and login to the system. Only then can you begin. When you are in, set the first record in honor of your first step.</p>
<p>Have you not done yet? Get Started! I am absolutely serious, 100%. If you do not do this now, then a chance that you will not begin to do it later, will be even higher. Without this technique, the rest of the work will lead to a fail. Regardless of how you feel about it, it should be done.</p>
<p>When you have your form (and only then), you can move on. The second step is to determine what you do in the next few weeks. It will be very little changes. Again, it may seem that this is not serious, but it should be. Therefore, you need to choose a small number of simple, useful things that you will do regularly. Here it is useful to use LIR mentioned above. These actions should not cause a huge internal resistance (although there should be some). You can choose almost anything you like, but the main thing that they do not exceed the levels 4 or 5. Importantly, these actions should be obvious, simple; over which one you should not think, just mechanically perform.</p>
<p>I will give some examples: do some cleaning in the room / apartment (and constantly maintain order), monitor your hygiene (regularly taking a bath / shower, brush your teeth - all consider separately, the effect must be marked in your TRS board) and so on. It should be carried out every day, regularly, i.e. where you procrastinated once, there will be other times, the third, and then fail.</p>
<p>It is important that the rest of your life and comfort zone should not be changed. You will keep doing what you were doing before. Therefore, it will be necessary for several weeks.</p>
<h3><a name='a13' href='#content'><em>Future Plans</em></a></h3>
<p>You have to write down all that you want to achieve. Your life plans for this year or any other time soon. Start working, move out from your parents, successfully complete your studies - anything. When you have listed it, you can mark it using LIR, it is not necessary, but it will be interesting to compare later. After that, you can put this list of paper somewhere, but not too far away, so you can find later.</p>
<h3><a name='a14' href='#content'><em>Reminders</em></a></h3>
<p>It is important to begin to make reminders. As you guessed, they should remind you that it is necessary to perform the actions that you set for yourself. What could it be? Firstly, something that is in the place of your frequent stay. For example, any figure or note on the computer desk.</p>
<p>This reminder should be in plain view, preferably bright colors to catch the eye. You can quickly get used to. Therefore, it is necessary to make new ones. About once a week. Put the creating of reminders into your TRS board.</p>
<p>Secondly, I would recommend to use alarms. Surely, you have it in your phone. It is brilliant, if you can create several signals at different times for different things. When the alarm rings, then you immediately stop what you were doing before, move it from the chair, and begin to carry out planned activities. Right, that is important.</p>
<h3><a name='a15' href='#content'><em>Breakdowns</em></a></h3>
<p>If your case is serious, it is possible to break even at this stage. What does it mean to break? This is when you start to put off even these simple tasks. Frustration begins when you, as usual, make something from your comfort zone, and you cannot stop even for a short while. Moreover, you cannot stop it; otherwise, fail is guaranteed. Therefore, you have to balance on the edge. There is no other way.</p>
<p>As a result of failure you go deeper into the comfort zone (and it gives you a little more fun than usual), you think that you will make it later (think about the illusion of the brain that I brought in the theoretical part). As a result, day passes, then another, and you do not do what you should. Bring yourself to do it will be harder than it was originally. I guarantee it. Therefore, the whole system can go down the drain as long as you cannot realize again that something needs to be changed (and that can take a long time).</p>
<p>If you are motivated, you do this with responsibility, trying not to delay, marking all the achievements at once on the board (this is important), then this should not happen at this stage. But what if it did happen? It is necessary as soon as possible to get back into doing the things that you stated for yourself. And try to accomplish this as quickly as possible. After the completion of any task put on the board a symbol of a higher value. Quickly coming back - it really is a higher achievement than just perform these actions. But I hope that even at this stage it does not happen.</p>
<p>When it is necessary to proceed to the next stage? Everything is very simple. During these weeks, actions you perform must begin to enter the comfort zone or even get into it. Determine this is also very easy: the internal resistance against these actions should disappear. Well, at least it should weaken. If this happens, then I congratulate you, you are in the right direction and we can move on.</p>
<h2><a name='a16' href='#content'><strong>Stage 2</strong></a></h2>
<h3><a name='a17' href='#content'><em>New goals</em></a></h3>
<p>You keep doing what you did before. Only now, add some new tasks. They should be a bit more complicated, but not very much. And they should be even more beneficial. The choice is wide and there is already associated with your development itself. First, you choose some one thing that you are interested in, I think it useful to help in achieving your future goals. This can be exercising (joining some sport community will serve as an extra motivation), learning a foreign language, learning to draw, learn a programming language and so on. For those who learn, I would recommend to increase the knowledge and skills if it is relatedto the profession. But this is only if you are interested. That is totally up to you. But remember, it has to be one thing, so beware.</p>
<p>Have you chose it? Awesome! If you chose to start the exercise, it is easy and there should be no big difficulties. However, if you chose the development of a skill that requires minimal incorporation of the brain, it can be difficult. And the difficulty here is that we want to delay actions that we do not clearly understand. We did not have the experience or it was insignificant in this area.</p>
<p>There was one experiment, I do not remember where I came across it (it was a long time ago). It concludes that the students listened to a lecture (or something like that). After that, they had to write some report of what they have learned. The students were divided into three groups:</p>
<ol>
<li>The first group was told to write a report, no instructions, no reward.</li>
<li>The second group was given some financial reward, but the experimenters did not explained anything.</li>
<li>The third group received detailed instructions on how to write a report that they had to do in this case, but paid nothing.</li>
</ol>
<p>Guess which group had the highest percentage of reports?</p>
<p>The third. Even despite the fact that they were not paid, they still did most of the reports. Again, this is our brain; it is trying to avoid the unknown and uncertainty.</p>
<h3><a name='a18' href='#content'><em>Making detailed plan</em></a></h3>
<p>But this problem can be dealt with relatively easily. The fact is that we can create detailed instructions for themselves. Something like to do - list. Thus, with each complex thing we will not start with the implementation of the case but with an additional zero point - a plan for the implementation of this thing.</p>
<p>It would seem that additional steps would complicate our work. But in fact, to force myself to write the instructions and begin the first concrete step is much easier than without preparation start is not entirely clear case. In order to write this statement, we have all the possibilities: the Internet and other more experienced people. Just google first important guides, articles, books, or anything else. When most of the required information has been received, perhaps we still have left a couple of specific questions, the answers to which we have not been able to find.</p>
<p>These questions should referred to specialists. But I repeat, it should only be done if you were looking for the information yourself. Why not turn to experienced people at once and torture them with your simple questions? It is simple: First, it is just rude to rob people&rsquo;s time because of your own laziness and procrastination, when you could find most of the information for yourself. Second, experienced people will be aware that you are just lazy and blatantly trying rob their valuable time. Even if a person was initially quite good, friendly and willing to answer a few questions, then when he heard a thousand and one stupid question, this person will just send you to hell. And he will be right.</p>
<p>I will give one example here. Students should understand it very well. This is just an example; it does not mean that you are supposed to do something like that. So, who studied should know well how to write term papers. Anyone who has ever done it, faced with a hell of procrastination.</p>
<p>So, you have to write your final project. &quot;I have a lot of time. I will start next week&quot; and so on. Familiar? Not so much students really know how to write term papers. They face a challenge that they have not performed and an idea of how to do it is not very clear, and they do not know where to start either. A right decision would be to start immediately and google some sources on how this has to be done.</p>
<p>After reading this materials, you have to choose a topic and the supervisor if you have not done so. And you make a plan of writing. I am going to show it, it is very rough, just for instance, in real life there may be some additional points. So, the plan is as follows:</p>
<ol>
<li>Study the literature, clarify the topic, and formulate an initial thesis.</li>
<li>Clarify it with the supervisor (if your lecturer is normal, not a procrastinator, he or she will work with you throughout the writing, but will not do anything for you).</li>
<li>Collect material for the theoretical study on the topic.</li>
<li>Write an introduction and a theoretical part.</li>
<li>If it is necessary to carry out practical research, then make additional plan and execute it.</li>
<li>To analyze the results, to understand whether the thesis is confirmed, to formulate conclusions.</li>
<li>Write the practical part, conclusions.</li>
<li>Pass the work.</li>
</ol>
<p>Again, this is a rough plan. In fact, anything can be added (especially depending on your occupation), as well as detailed plans should very clearly and in detail specify your actions. For example, in the first point it is necessary to write down what exactly do you have to google / search for, download, read the downloaded and if it is not enough, go to the library for more literature, which is not in the network, and so on. I repeat, every action must be noted. Not in the head, on paper or on a computer.</p>
<p>You need to make a plan of your chosen activity based on this example for the next step in overcoming procrastination. In the process, you can improve it. Note performance of every small step on your TRS board. Completion of a large part consists of these small steps (despite the fact that they have already been exposed in the blank) is also celebrated, but with a more important symbol (level 5).</p>
<h3><a name='a19' href='#content'><em>One more trap</em></a></h3>
<p>I would like to note that in terms of development of any skill, there is one catch, which may run into some people. I have often seen this among friends, sometimes it happened to me. When a person meets the first difficulties and setbacks, he has sharply lost the desire to continue to do it and he throws the case. This is a complex problem. To get around by her side at least at this stage, you need to consider the following points:</p>
<ol>
<li>Do not choose a very complicated matter.</li>
<li>Choose what you really want.</li>
</ol>
<p>There are ways to cope with it. Briefly talk about the already mentioned REBT. The fact that such a loss of motivation (and other irrational negative feelings) are associated with irrational beliefs that we have a lot. In this particular case, it is &quot;I have everything to be obtained quickly and easily&quot;, &quot;I have to do everything perfectly,&quot; &quot;I should turn out all right&quot;. And when a person has something that does not work, it causes severe inadequate reaction. Generally, there is always negative emotions. But when they impede the implementation of something, they called irrational. To make the negative emotions less affective, you change their beliefs. Instead of &quot;should&quot; use &quot;I would like&quot; and the severity of demands on yourself will be reduced. As a result, our beliefs must be transformed into something like this: &quot;I wish that I had all turned out very easily, and if it will not, it&rsquo;s okay&quot;, &quot;I want to do well&quot;, etc. With such appropriate beliefs and attitudes with things that you cannot make immediately and easily, will not appear so much negative emotions that can ruin your initiative. You will have to write down all your irrational beliefs and change them like in the example above to rational.</p>
<p>I understand that the information I have here as an explanation is not enough, but I do not want to write down the details of REBT, otherwise this page will be two times bigger. Therefore, I strongly recommend toget acquainted with REBT. There is no harm to learn something new, and it will be useful in the future, not only to deal with procrastination. But I do not recommend to get acquainted with the REBT with the help of some very unfortunate articles from the Internet. It shows some basic concepts, but they are taken out of context of Ellis&rsquo;s explanations. So better to get his book &quot;The practice of rational-emotive behavioral therapy&quot;.</p>
<p>And if I am speaking about the REBT, I would say that there is a very good book (or rather &quot;workbook&quot;) to fight procrastination. The Procrastination Workbook, William Knaus.</p>
<h3><a name='a20' href='#content'><em>Looking for a partner</em></a></h3>
<p>Returning to the topic of this stage, I would like to tell you about one more thing that can generate extra motivation. The thing is that you have to find someone who will talk about his or her goals and achievements. It really can increase motivation. Find a man who will really be interested in your achievements is not so simple. You can certainly find among those who is also working on this program or just individually developing some skills. However, this poses some danger.</p>
<p>The problem is that if the other person starts to procrastinate, breaks, will stop reporting their achievements and are avoid making contact (if not break any connection with you), then you can go down with this person. And that&rsquo;s bad. If you decide to do your program someone else, and if you have this situation happens, immediately change your partner.</p>
<p>The second problem is that you may get beliefs that I mentioned in the theoretical part: you will think that you have to report, but do not want to. And if you should do something, you automatically getting the negative association, of which I spoke. Always consider and try to avoid this.</p>
<p>So, you do your chosen activity daily for about 1-2 weeks. During this time, it should start entering your comfort zone, so the inner resistance must decrease. If everything is all right, you choose your own second activity on the same principle described above. Do not stop everything that you were doing before.</p>
<p>I have to say what you have to do if your first chosen activity is not a part of the comfort zone yet. Here are the following reasons:</p>
<ol>
<li>It is not interesting.</li>
<li>You do not achieve good results, which you would be proud of.</li>
</ol>
<p>If so, you should not throw it, but continue to engage in a week. And after the third week pick your next activity. If you still have some difficulties, then simply reduce the pressure and pay more attention to a new activity, but do not throw the old one. However, if the first session is so hard for you that you just will not break or have broken already, you should not continue to carry it out. You can quit, but only if it really spoils you with everything. In this case there is some danger. It is so possible to throw all undertakings and for the year do not go further. I have seen these people. It is very bad sight.</p>
<p> </p>
<h3><a name='a21' href='#content'><em>Breakdowns again</em></a></h3>
<p>Again, attention should be paid to breakdowns. Unfortunately, at this stage, their probability is even higher. It is important to take into account all that I have written before, and perform avoid a breakdown. And this is really important. But if there was a breakdown, the tactics of conduct should be a little different. If the failure has affected all activities, so you no longer even perform the simple actions that you chose at the first stage, you need to start doing it again as soon as possible.</p>
<p>However, with the start of the second stage it is necessary to wait a little bit. Do not touch them for a few days. Then start again with your first activity (if it did not caused a break), then start the second in a week. Try to consider what caused the failure and do not allow this.</p>
<p>Then you move on to the above scenario, and eventually (but not too much in a hurry) add 1-2 new activities. In this regard, there is need to rush. You have some significant achievements already, good comfort zone must expanded, and the inner resistance must be weaker by now. That is, many new actions that are not in your comfort zone, should not cause many unpleasant experiences inside when you make them, as it would before.</p>
<p>If it is true, then you are moving in a right direction and can go further. Do not completely quit on old habits. Of course, you have less time for them, but if you enjoyed them and they still able to make you happier &ndash; it makes sense to leave them in your comfort zone. Moreover, they must be more enjoyable by now because of reasons described above.</p>
<h2><a name='a22' href='#content'><strong>The last stage</strong></a></h2>
<h3><a name='a23' href='#content'><em>Implement the initial purpose</em></a></h3>
<p>Do you remember of the list of your goals written in the beginning? Things you want to achieve. We came close to this. It should no longer be such an undefeatable wall, as it was in the beginning. To begin, we must once again write our goals in detail. Very detailed, every single action is very important! If some things are not known, you have to look for information, or leave them for the moment when it will become clearer. Did you? Begin to perform. But do not hurry. You will still be doing what you were doing before. And you still can not overwork, it is fatal.</p>
<h3><a name='a24' href='#content'><em>Do it now</em></a></h3>
<p>I would like to talk about the principle of Neil Fiore described in his book &ldquo;Do it now&rdquo;. As it was possible to understand, the principle is to develop a habit of doing anything at once. A good technique if you really work on it. Personally, I use it with my work. A concrete example: when a customer orders something, I start to implement it immediately. Immediately means that I am not going to make myself some tea, check the mail or do something else, I literally start at the exact moment when I got an assignment.</p>
<p>Once the conversation is finished, without being distracted by anything, I&rsquo;m starting to think of what exactly I have to implement, to draw up plans. Or google some information that I am missing. Only then, I can be distracted by something and rest a bit, but it is not the Internet. You know very well that the fifteen-minute break could end an hour or more spent in vain. After the break, I start doing the thing. After finishing the first draft, I have to do something else, it still has to lie for a while, then I look at it with fresh eyes and right all the wrongs.</p>
<p>Of course, this principle can be used earlier in the instruction. You could already use it on the second stage. It is up to you. The only thing I want to say that it should not be extend to everything. On the one hand this is good, on the other hand, sooner or later you will still start delay something, &ldquo;for half an hour&rdquo;, then it is very easy to fail. Select some areas that it is critical to use this principle and use it there without any exceptions or delaying.</p>
<h3><a name='a25' href='#content'><em>Recommendations</em></a></h3>
<ol>
<li>Do not forget about your TRS board. Continue to use it. Observe and mark each step on the way to achieving the goals. And your new achievements should be marked with even more important levels.</li>
<li>Look for additional methods of self-motivation. You can find it on the Internet or invent your own.</li>
<li>Do not overreach and control your stress level. Here are some helpful relaxation techniques. You can about them read on the Internet (google &ldquo;technique of neuromuscular relaxation&rdquo; and &ldquo;autogenic training&rdquo;, but not the original Schulz, because there is some esoteric nonsense at the end).</li>
</ol>
<h2><a name='a26' href='#content'><strong>Afterword</strong></a></h2>
<p>In conclusion, I would like to say that I hope very much that this project will help someone. I wrote it for you, and I hope that the free time that I ripped from games and movies, was spent with benefit.</p>
<p>Finally, if you decide to follow the guidance, I want to say once again that really need to do things written here. One reading is not enough. No need to complain that my technique does not work if you do not even deign to create an account here.</p>
</div>
<hr>
<h2>Proceed to <a class='btn btn-success btn-lg' href='/register.php' role='button'>Registration</a></h2>
<hr>
</div>
<div id='bottom'></div>
</div>
</body>
</html>";

?>